import type {
  Alert,
  Approval,
  Communication,
  Contractor,
  Customer,
  DocumentationArtifact,
  Invoice,
  Lead,
  Job,
  ContractorAssignment,
  DemoScenario
} from "@/types/core";

export const mockDashboardMetrics = {
  openJobs: 18,
  jobsScheduledToday: 5,
  jobsCompletedThisWeek: 9,
  outstandingInvoices: 7,
  revenueThisWeek: 28450,
  contractorPayoutsPending: 6,
  missedCommunications: 4,
  leadsRequiringFollowUp: 3,
  jobsMissingDocumentation: 5,
  jobsReadyForInvoiceReview: 4,
  safetyExceptions: 2
};

export const mockQueues = [
  {
    title: "Approval queue",
    items: [
      { id: "apq-1", title: "Invoice release approval", detail: "Michael Keegan final approval required" },
      { id: "apq-2", title: "Documentation exception", detail: "Ramp install photos need review" }
    ]
  },
  {
    title: "Alert center",
    items: [
      { id: "alt-1", title: "Lead follow-up overdue", detail: "Missed call has no logged response" },
      { id: "alt-2", title: "PPE status exception", detail: "Contractor compliance status requires review" }
    ]
  },
  {
    title: "Invoice readiness",
    items: [
      { id: "inv-1", title: "Job FLR-1042", detail: "Completion notes received, photo set incomplete" },
      { id: "inv-2", title: "Job FLR-1048", detail: "Ready for human invoice review" }
    ]
  }
];

export const mockLeads: Lead[] = [
  {
    id: "lead_001",
    leadId: "lead_001",
    customerId: "customer_001",
    contactName: "M. Reynolds",
    leadType: "Ramp install",
    status: "converted",
    source: "Manual phone intake",
    owner: "Office Admin",
    nextStep: "Review documentation and move job toward invoice readiness.",
    relatedCommunicationId: "communication_001",
    notes: "Converted into job FLR-1042."
  },
  {
    id: "lead_002",
    leadId: "lead_002",
    customerId: "customer_002",
    contactName: "WilScot account",
    leadType: "Commercial ramp takedown",
    status: "converted",
    source: "Manual commercial intake",
    owner: "Office Admin",
    nextStep: "Finance review before client-facing invoice release.",
    relatedCommunicationId: "communication_002",
    notes: "Converted into job FLR-1048."
  },
  {
    id: "lead_003",
    leadId: "lead_003",
    customerId: "customer_003",
    contactName: "S. Patel",
    leadType: "Ramp estimate",
    status: "estimate_needed",
    source: "Website/manual lead",
    owner: "Office Admin",
    nextStep: "Call back and schedule estimate.",
    relatedCommunicationId: "communication_003",
    notes: "Lead exists to validate intake before HubSpot sync."
  },
  {
    id: "lead_004",
    leadId: "lead_004",
    customerId: "customer_004",
    contactName: "A. Martin",
    leadType: "Residential ramp install",
    status: "converted",
    source: "Demo Scenario 1",
    owner: "Dispatcher",
    nextStep: "Contractor acceptance and field documentation.",
    relatedCommunicationId: "communication_004",
    notes: "Demo lead converted into residential ramp install job."
  },
  {
    id: "lead_005",
    leadId: "lead_005",
    customerId: "customer_005",
    contactName: "WilScot coordinator",
    leadType: "Commercial service call",
    status: "converted",
    source: "Demo Scenario 2",
    owner: "Office Admin",
    nextStep: "Review closeout documentation.",
    relatedCommunicationId: "communication_005",
    notes: "Commercial account request converted into service job."
  },
  {
    id: "lead_006",
    leadId: "lead_006",
    customerId: "customer_006",
    contactName: "D. Nguyen",
    leadType: "VPL installation",
    status: "qualified",
    source: "Demo Scenario 3",
    owner: "Dispatcher",
    nextStep: "Confirm specialized equipment before dispatch-ready state.",
    relatedCommunicationId: "communication_006",
    notes: "Qualified specialized install lead."
  },
  {
    id: "lead_007",
    leadId: "lead_007",
    customerId: "customer_007",
    contactName: "C. Brooks",
    leadType: "Ramp takedown",
    status: "converted",
    source: "Demo Scenario 4",
    owner: "Office Admin",
    nextStep: "Recover missing after photos.",
    relatedCommunicationId: "communication_007",
    notes: "Lead converted but closeout is blocked by documentation."
  },
  {
    id: "lead_008",
    leadId: "lead_008",
    customerId: "customer_008",
    contactName: "Facilities manager",
    leadType: "Commercial ramp install",
    status: "converted",
    source: "Demo Scenario 5",
    owner: "Finance",
    nextStep: "Michael invoice release approval.",
    relatedCommunicationId: "communication_008",
    notes: "Commercial install is ready for invoice approval."
  }
];

export const mockCustomers: Customer[] = [
  {
    id: "customer_001",
    customerId: "customer_001",
    customerType: "residential",
    displayName: "M. Reynolds",
    status: "active",
    primaryContactName: "M. Reynolds",
    primaryContactPhone: "(555) 013-0101",
    primaryContactEmail: "mock.customer@example.com",
    source: "Manual intake",
    notes: "Ramp install customer. HubSpot sync intentionally excluded."
  },
  {
    id: "customer_002",
    customerId: "customer_002",
    customerType: "commercial",
    displayName: "WilScot account",
    status: "active",
    primaryContactName: "Commercial coordinator",
    primaryContactPhone: "(555) 013-0102",
    primaryContactEmail: "mock.commercial@example.com",
    source: "Manual commercial account",
    notes: "Commercial account placeholder for WillScot-style work."
  },
  {
    id: "customer_003",
    customerId: "customer_003",
    customerType: "residential",
    displayName: "S. Patel",
    status: "prospect",
    primaryContactName: "S. Patel",
    primaryContactPhone: "(555) 013-0103",
    primaryContactEmail: "mock.intake@example.com",
    source: "Website/manual lead",
    notes: "Needs estimate callback."
  },
  {
    id: "customer_004",
    customerId: "customer_004",
    customerType: "residential",
    displayName: "Residential Ramp Install Demo",
    status: "active",
    primaryContactName: "A. Martin",
    primaryContactPhone: "(555) 013-0104",
    primaryContactEmail: "ramp.demo@example.com",
    source: "Demo Scenario 1",
    notes: "End-to-end residential ramp install journey."
  },
  {
    id: "customer_005",
    customerId: "customer_005",
    customerType: "commercial",
    displayName: "WilScot Service Call Demo",
    status: "active",
    primaryContactName: "WilScot coordinator",
    primaryContactPhone: "(555) 013-0105",
    primaryContactEmail: "wilscot.demo@example.com",
    source: "Demo Scenario 2",
    notes: "Service call journey with commercial coordination."
  },
  {
    id: "customer_006",
    customerId: "customer_006",
    customerType: "residential",
    displayName: "VPL Installation Demo",
    status: "active",
    primaryContactName: "D. Nguyen",
    primaryContactPhone: "(555) 013-0106",
    primaryContactEmail: "vpl.demo@example.com",
    source: "Demo Scenario 3",
    notes: "VPL install journey focused on dispatch and documentation."
  },
  {
    id: "customer_007",
    customerId: "customer_007",
    customerType: "residential",
    displayName: "Documentation Missing Demo",
    status: "active",
    primaryContactName: "C. Brooks",
    primaryContactPhone: "(555) 013-0107",
    primaryContactEmail: "docs.demo@example.com",
    source: "Demo Scenario 4",
    notes: "Journey intentionally blocked by missing contractor documentation."
  },
  {
    id: "customer_008",
    customerId: "customer_008",
    customerType: "commercial",
    displayName: "Invoice Approval Demo",
    status: "active",
    primaryContactName: "Facilities manager",
    primaryContactPhone: "(555) 013-0108",
    primaryContactEmail: "invoice.demo@example.com",
    source: "Demo Scenario 5",
    notes: "Journey ready for Michael invoice release approval."
  }
];

export const mockJobs: Job[] = [
  {
    id: "job_001",
    jobId: "job_001",
    jobNumber: "FLR-1042",
    customerId: "customer_001",
    customerName: "M. Reynolds",
    jobType: "Ramp install",
    status: "documentation_review",
    siteAddress: "Residential site, Tampa area",
    scheduledFor: "Today",
    assignedTo: "Lead Installer A",
    documentationStatus: "needs_review",
    invoiceReadinessStatus: "blocked",
    invoiceReadyForReview: false,
    invoiceReadiness: "Blocked by missing install photos",
    notes: "Completion notes received. Photos need human review."
  },
  {
    id: "job_002",
    jobId: "job_002",
    jobNumber: "FLR-1048",
    customerId: "customer_002",
    customerName: "WilScot account",
    jobType: "Ramp takedown",
    status: "invoice_review",
    siteAddress: "Commercial site, Orlando area",
    scheduledFor: "This week",
    assignedTo: "Senior Lead B",
    documentationStatus: "approved",
    invoiceReadinessStatus: "ready_for_review",
    invoiceReadyForReview: true,
    invoiceReadiness: "Ready for human invoice review",
    notes: "Do not release client-facing invoice without Michael approval."
  },
  {
    id: "job_003",
    jobId: "job_003",
    jobNumber: "FLR-1051",
    customerId: "customer_003",
    customerName: "S. Patel",
    jobType: "Ramp estimate",
    status: "scheduled",
    siteAddress: "Residential site, Sarasota area",
    scheduledFor: "Tomorrow",
    assignedTo: "Unassigned",
    documentationStatus: "required",
    invoiceReadinessStatus: "not_ready",
    invoiceReadyForReview: false,
    invoiceReadiness: "Not ready",
    notes: "Dispatch assignment still pending."
  },
  {
    id: "job_004",
    jobId: "job_004",
    jobNumber: "FLR-2001",
    customerId: "customer_004",
    customerName: "Residential Ramp Install Demo",
    jobType: "Residential ramp install",
    status: "assigned",
    siteAddress: "Residential site, Clearwater area",
    scheduledFor: "Today",
    assignedTo: "Lead Installer A",
    documentationStatus: "required",
    invoiceReadinessStatus: "not_ready",
    invoiceReadyForReview: false,
    invoiceReadiness: "Not ready until completion documentation is submitted",
    notes: "Scenario 1: assigned and ready for contractor acceptance."
  },
  {
    id: "job_005",
    jobId: "job_005",
    jobNumber: "FLR-2002",
    customerId: "customer_005",
    customerName: "WilScot Service Call Demo",
    jobType: "WilScot service call",
    status: "in_progress",
    siteAddress: "Commercial site, Lakeland area",
    scheduledFor: "Today",
    assignedTo: "Senior Lead B",
    documentationStatus: "submitted",
    invoiceReadinessStatus: "needs_review",
    invoiceReadyForReview: false,
    invoiceReadiness: "Waiting on documentation review",
    notes: "Scenario 2: service call underway with submitted notes."
  },
  {
    id: "job_006",
    jobId: "job_006",
    jobNumber: "FLR-2003",
    customerId: "customer_006",
    customerName: "VPL Installation Demo",
    jobType: "VPL installation",
    status: "scheduled",
    siteAddress: "Residential site, Naples area",
    scheduledFor: "Tomorrow",
    assignedTo: "Lead Installer A",
    documentationStatus: "required",
    invoiceReadinessStatus: "not_ready",
    invoiceReadyForReview: false,
    invoiceReadiness: "Not ready until install completion",
    notes: "Scenario 3: VPL install scheduled and preparing dispatch."
  },
  {
    id: "job_007",
    jobId: "job_007",
    jobNumber: "FLR-2004",
    customerId: "customer_007",
    customerName: "Documentation Missing Demo",
    jobType: "Ramp takedown",
    status: "transfer_review",
    siteAddress: "Residential site, Fort Myers area",
    scheduledFor: "Yesterday",
    assignedTo: "Helper C",
    documentationStatus: "missing",
    invoiceReadinessStatus: "blocked",
    invoiceReadyForReview: false,
    invoiceReadiness: "Blocked until transfer closeout and after photos are complete",
    notes: "Scenario 4: partial takedown needs another qualified contractor to finish closeout.",
    transferStatus: "transfer_requested",
    transferReason: "Original contractor could not complete after-photo closeout and remaining site verification.",
    remainingScope: "Return to site, verify no trip hazard remains, capture after photos, and submit completion notes.",
    previousAssignee: "Helper C",
    transferTarget: "Lead Installer A or Senior Lead B",
    transferPacketSummary:
      "Partial takedown completed. Billing stays blocked until a new contractor finishes verification and proof-of-work."
  },
  {
    id: "job_008",
    jobId: "job_008",
    jobNumber: "FLR-2005",
    customerId: "customer_008",
    customerName: "Invoice Approval Demo",
    jobType: "Commercial ramp install",
    status: "invoice_review",
    siteAddress: "Commercial site, Jacksonville area",
    scheduledFor: "Completed this week",
    assignedTo: "Senior Lead B",
    documentationStatus: "approved",
    invoiceReadinessStatus: "ready_for_review",
    invoiceReadyForReview: true,
    invoiceReadiness: "Ready for Michael approval",
    notes: "Scenario 5: complete and ready for client-facing invoice approval."
  }
];

export const mockContractors: Contractor[] = [
  {
    id: "contractor_001",
    contractorId: "contractor_001",
    fullName: "Lead Installer A",
    phone: "(555) 013-0201",
    email: "lead.installer@example.com",
    role: "Lead Installer",
    status: "lead_installer",
    payType: "split",
    defaultRateOrSplit: "Standard lead split",
    serviceAreas: ["Tampa", "St. Petersburg"],
    skills: ["Ramp install", "Service / repair"],
    vehicleAccess: "Yes",
    toolAccess: "Yes",
    ppeComplianceStatus: "Compliant",
    safetyTrainingStatus: "Current",
    notes: "Eligible for assigned ramp install work."
  },
  {
    id: "contractor_002",
    contractorId: "contractor_002",
    fullName: "Senior Lead B",
    phone: "(555) 013-0202",
    email: "senior.lead@example.com",
    role: "Senior Lead",
    status: "senior_lead",
    payType: "rate",
    defaultRateOrSplit: "Senior lead rate",
    serviceAreas: ["Orlando", "Central Florida"],
    skills: ["Ramp takedown", "WilScot work"],
    vehicleAccess: "Yes",
    toolAccess: "Yes",
    ppeComplianceStatus: "Review needed",
    safetyTrainingStatus: "Current",
    notes: "PPE review should stay visible in alert center."
  },
  {
    id: "contractor_003",
    contractorId: "contractor_003",
    fullName: "Helper C",
    phone: "(555) 013-0203",
    email: "helper@example.com",
    role: "Helper",
    status: "helper",
    payType: "hourly",
    defaultRateOrSplit: "Helper hourly",
    serviceAreas: ["Tampa"],
    skills: ["Ramp install support"],
    vehicleAccess: "No",
    toolAccess: "Shared",
    ppeComplianceStatus: "Compliant",
    safetyTrainingStatus: "Current",
    notes: "Assigned only with lead installer."
  }
];

export const mockCommunications: Communication[] = [
  {
    id: "communication_001",
    communicationId: "communication_001",
    communicationType: "call",
    direction: "inbound",
    status: "unanswered",
    sourceChannel: "Phone",
    contactName: "M. Reynolds",
    relatedObjectType: "Job",
    relatedObjectId: "job_001",
    summary: "Customer requested ETA confirmation.",
    followUpOwner: "Office Admin"
  },
  {
    id: "communication_002",
    communicationId: "communication_002",
    communicationType: "email",
    direction: "outbound",
    status: "needs_review",
    sourceChannel: "Email",
    contactName: "WilScot account",
    relatedObjectType: "Job",
    relatedObjectId: "job_002",
    summary: "Completion packet question needs human review before send.",
    followUpOwner: "Office Admin"
  },
  {
    id: "communication_003",
    communicationId: "communication_003",
    communicationType: "manual_note",
    direction: "internal",
    status: "new",
    sourceChannel: "Manual note",
    contactName: "S. Patel",
    relatedObjectType: "Customer",
    relatedObjectId: "customer_003",
    summary: "Needs estimate callback.",
    followUpOwner: "Office Admin"
  },
  {
    id: "communication_004",
    communicationId: "communication_004",
    communicationType: "call",
    direction: "inbound",
    status: "received",
    sourceChannel: "Phone",
    contactName: "A. Martin",
    relatedObjectType: "Job",
    relatedObjectId: "job_004",
    summary: "Customer confirmed ramp install access window.",
    followUpOwner: "Dispatcher"
  },
  {
    id: "communication_005",
    communicationId: "communication_005",
    communicationType: "email",
    direction: "inbound",
    status: "needs_review",
    sourceChannel: "Email",
    contactName: "WilScot coordinator",
    relatedObjectType: "Job",
    relatedObjectId: "job_005",
    summary: "WilScot requested service call closeout confirmation.",
    followUpOwner: "Office Admin"
  },
  {
    id: "communication_006",
    communicationId: "communication_006",
    communicationType: "manual_note",
    direction: "internal",
    status: "new",
    sourceChannel: "Manual note",
    contactName: "D. Nguyen",
    relatedObjectType: "Job",
    relatedObjectId: "job_006",
    summary: "VPL installation requires equipment confirmation before dispatch.",
    followUpOwner: "Dispatcher"
  },
  {
    id: "communication_007",
    communicationId: "communication_007",
    communicationType: "call",
    direction: "outbound",
    status: "unanswered",
    sourceChannel: "Phone",
    contactName: "C. Brooks",
    relatedObjectType: "Job",
    relatedObjectId: "job_007",
    summary: "Follow-up needed for missing after photos.",
    followUpOwner: "Office Admin"
  },
  {
    id: "communication_008",
    communicationId: "communication_008",
    communicationType: "email",
    direction: "internal",
    status: "needs_review",
    sourceChannel: "Email",
    contactName: "Facilities manager",
    relatedObjectType: "Invoice",
    relatedObjectId: "invoice_008",
    summary: "Invoice release packet ready for final review.",
    followUpOwner: "Finance"
  }
];

export const mockDocumentation: DocumentationArtifact[] = [
  {
    id: "documentation_001",
    documentationArtifactId: "documentation_001",
    artifactType: "Install photos",
    relatedObjectType: "Job",
    relatedObjectId: "job_001",
    jobNumber: "FLR-1042",
    submittedBy: "Lead Installer A",
    status: "submitted",
    source: "Contractor portal mock",
    reviewGate: "Needs review",
    notes: "Photo set incomplete."
  },
  {
    id: "documentation_002",
    documentationArtifactId: "documentation_002",
    artifactType: "Completion notes",
    relatedObjectType: "Job",
    relatedObjectId: "job_002",
    jobNumber: "FLR-1048",
    submittedBy: "Senior Lead B",
    status: "approved",
    source: "Manual admin review",
    reviewGate: "Ready for invoice",
    notes: "Approved for billing evidence."
  },
  {
    id: "documentation_003",
    documentationArtifactId: "documentation_003",
    artifactType: "Safety checklist",
    relatedObjectType: "Job",
    relatedObjectId: "job_003",
    jobNumber: "FLR-1051",
    submittedBy: "Dispatcher",
    status: "missing",
    source: "Manual requirement",
    reviewGate: "Blocked",
    notes: "Must be present before dispatch-ready state."
  },
  {
    id: "documentation_004",
    documentationArtifactId: "documentation_004",
    artifactType: "Install checklist",
    relatedObjectType: "Job",
    relatedObjectId: "job_004",
    jobNumber: "FLR-2001",
    submittedBy: "Lead Installer A",
    status: "required",
    source: "Demo Scenario 1",
    reviewGate: "Required before completion",
    notes: "Contractor must submit before closeout."
  },
  {
    id: "documentation_005",
    documentationArtifactId: "documentation_005",
    artifactType: "Service notes",
    relatedObjectType: "Job",
    relatedObjectId: "job_005",
    jobNumber: "FLR-2002",
    submittedBy: "Senior Lead B",
    status: "submitted",
    source: "Demo Scenario 2",
    reviewGate: "Needs review",
    notes: "Closeout notes submitted for WilScot service call."
  },
  {
    id: "documentation_006",
    documentationArtifactId: "documentation_006",
    artifactType: "VPL install prep",
    relatedObjectType: "Job",
    relatedObjectId: "job_006",
    jobNumber: "FLR-2003",
    submittedBy: "Dispatcher",
    status: "required",
    source: "Demo Scenario 3",
    reviewGate: "Required before dispatch-ready",
    notes: "Equipment and site readiness documentation required."
  },
  {
    id: "documentation_007",
    documentationArtifactId: "documentation_007",
    artifactType: "After photos",
    relatedObjectType: "Job",
    relatedObjectId: "job_007",
    jobNumber: "FLR-2004",
    submittedBy: "Helper C",
    status: "missing",
    source: "Demo Scenario 4",
    reviewGate: "Blocked",
    notes: "Missing photos block invoice readiness."
  },
  {
    id: "documentation_008",
    documentationArtifactId: "documentation_008",
    artifactType: "Completion packet",
    relatedObjectType: "Job",
    relatedObjectId: "job_008",
    jobNumber: "FLR-2005",
    submittedBy: "Senior Lead B",
    status: "approved",
    source: "Demo Scenario 5",
    reviewGate: "Ready for invoice",
    notes: "Completion packet approved."
  }
];

export const mockInvoices: Invoice[] = [
  {
    id: "invoice_001",
    invoiceId: "invoice_001",
    invoiceNumber: "Draft-1042",
    invoiceClass: "client",
    customerName: "M. Reynolds",
    status: "needs_review",
    amount: "$2,450",
    approvalOwner: "Office Admin",
    quickBooksReference: "Not synced",
    readinessSummary: "Missing documentation blocks invoice readiness."
  },
  {
    id: "invoice_002",
    invoiceId: "invoice_002",
    invoiceNumber: "Draft-1048",
    invoiceClass: "client",
    customerName: "WilScot account",
    status: "approved",
    amount: "$8,900",
    approvalOwner: "Michael Keegan",
    quickBooksReference: "Manual reference pending",
    readinessSummary: "Ready for final human release approval."
  },
  {
    id: "invoice_003",
    invoiceId: "invoice_003",
    invoiceNumber: "QB reference pending",
    invoiceClass: "client",
    customerName: "S. Patel",
    status: "draft",
    amount: "$0",
    approvalOwner: "Finance",
    quickBooksReference: "Not synced",
    readinessSummary: "Not ready. Estimate/job lifecycle incomplete."
  },
  {
    id: "invoice_004",
    invoiceId: "invoice_004",
    invoiceNumber: "Draft-2001",
    invoiceClass: "client",
    customerName: "Residential Ramp Install Demo",
    status: "draft",
    amount: "$3,200",
    approvalOwner: "Finance",
    quickBooksReference: "Not synced",
    readinessSummary: "Waiting on contractor documentation."
  },
  {
    id: "invoice_005",
    invoiceId: "invoice_005",
    invoiceNumber: "Draft-2002",
    invoiceClass: "client",
    customerName: "WilScot Service Call Demo",
    status: "needs_review",
    amount: "$1,150",
    approvalOwner: "Finance",
    quickBooksReference: "Not synced",
    readinessSummary: "Service documentation submitted; finance review required."
  },
  {
    id: "invoice_006",
    invoiceId: "invoice_006",
    invoiceNumber: "Draft-2003",
    invoiceClass: "client",
    customerName: "VPL Installation Demo",
    status: "draft",
    amount: "$0",
    approvalOwner: "Finance",
    quickBooksReference: "Not synced",
    readinessSummary: "Not ready until install completion."
  },
  {
    id: "invoice_007",
    invoiceId: "invoice_007",
    invoiceNumber: "Draft-2004",
    invoiceClass: "client",
    customerName: "Documentation Missing Demo",
    status: "held",
    amount: "$950",
    approvalOwner: "Office Admin",
    quickBooksReference: "Not synced",
    readinessSummary: "Held because documentation is missing."
  },
  {
    id: "invoice_008",
    invoiceId: "invoice_008",
    invoiceNumber: "Draft-2005",
    invoiceClass: "client",
    customerName: "Invoice Approval Demo",
    status: "needs_review",
    amount: "$12,400",
    approvalOwner: "Michael Keegan",
    quickBooksReference: "Not synced",
    readinessSummary: "Ready for Michael approval before client-facing release."
  }
];

export const mockAlerts: Alert[] = [
  {
    id: "alert_001",
    alertId: "alert_001",
    sourceObjectType: "Communication",
    sourceObjectId: "communication_001",
    severity: "high",
    status: "open",
    owner: "Office Admin",
    summary: "Missed call requires follow-up.",
    thresholdRule: "Communication unanswered after follow-up threshold"
  },
  {
    id: "alert_002",
    alertId: "alert_002",
    sourceObjectType: "Contractor",
    sourceObjectId: "contractor_002",
    severity: "medium",
    status: "acknowledged",
    owner: "Dispatcher",
    summary: "PPE compliance needs review.",
    thresholdRule: "Contractor PPE not compliant or pending review"
  },
  {
    id: "alert_003",
    alertId: "alert_003",
    sourceObjectType: "Job",
    sourceObjectId: "job_002",
    severity: "medium",
    status: "assigned",
    owner: "Finance",
    summary: "Job ready for invoice review.",
    thresholdRule: "Job entered invoice_review"
  },
  {
    id: "alert_004",
    alertId: "alert_004",
    sourceObjectType: "Job",
    sourceObjectId: "job_004",
    severity: "medium",
    status: "assigned",
    owner: "Dispatcher",
    summary: "Residential ramp install awaiting contractor acceptance.",
    thresholdRule: "Assigned job not yet accepted"
  },
  {
    id: "alert_005",
    alertId: "alert_005",
    sourceObjectType: "Communication",
    sourceObjectId: "communication_005",
    severity: "medium",
    status: "open",
    owner: "Office Admin",
    summary: "WilScot service closeout needs review.",
    thresholdRule: "Commercial communication needs review"
  },
  {
    id: "alert_006",
    alertId: "alert_006",
    sourceObjectType: "Job",
    sourceObjectId: "job_006",
    severity: "medium",
    status: "open",
    owner: "Dispatcher",
    summary: "VPL install needs equipment confirmation.",
    thresholdRule: "Scheduled specialized install missing prep confirmation"
  },
  {
    id: "alert_007",
    alertId: "alert_007",
    sourceObjectType: "DocumentationArtifact",
    sourceObjectId: "documentation_007",
    severity: "high",
    status: "open",
    owner: "Office Admin",
    summary: "After photos missing for completed takedown.",
    thresholdRule: "Required documentation missing"
  },
  {
    id: "alert_008",
    alertId: "alert_008",
    sourceObjectType: "Invoice",
    sourceObjectId: "invoice_008",
    severity: "high",
    status: "open",
    owner: "Finance",
    summary: "Invoice ready for Michael approval.",
    thresholdRule: "Client-facing invoice requires final human approval"
  }
];

export const mockApprovals: Approval[] = [
  {
    id: "approval_001",
    approvalId: "approval_001",
    approvalCategory: "Invoice approval",
    approvalType: "client_invoice_release",
    relatedObjectType: "Invoice",
    relatedObjectId: "invoice_002",
    status: "requested",
    requestedBy: "Finance",
    approver: "Michael Keegan",
    risk: "Client-facing financial action",
    targetTransition: "Invoice approved -> sent",
    evidenceSummary: "Invoice draft is ready for final human release review.",
    blockingRule: "Client-facing invoices require Michael Keegan approval in MVP.",
    decisionNotes: "Final release requires explicit human approval."
  },
  {
    id: "approval_002",
    approvalId: "approval_002",
    approvalCategory: "Documentation approval",
    approvalType: "documentation_exception",
    relatedObjectType: "DocumentationArtifact",
    relatedObjectId: "documentation_001",
    status: "held",
    requestedBy: "Office Admin",
    approver: "Office Admin",
    risk: "Missing photo evidence",
    targetTransition: "Documentation submitted -> approved",
    evidenceSummary: "Install photos were submitted but the set is incomplete.",
    blockingRule: "Billing/safety evidence must be reviewed by a human before approval.",
    decisionNotes: "Hold until required photo set is complete."
  },
  {
    id: "approval_003",
    approvalId: "approval_003",
    approvalCategory: "Payout approval",
    approvalType: "contractor_payout_review",
    relatedObjectType: "ContractorPayout",
    relatedObjectId: "mock_payout_batch_001",
    status: "requested",
    requestedBy: "Finance",
    approver: "Finance",
    risk: "Payment-adjacent review",
    targetTransition: "ContractorPayout needs_review -> approved",
    evidenceSummary: "Mock payout batch requires finance review before contractor release visibility.",
    blockingRule: "Contractor payouts cannot be approved without linked jobs and calculation basis.",
    decisionNotes: "Payout review only. No payment processing in MVP scaffold."
  },
  {
    id: "approval_004",
    approvalId: "approval_004",
    approvalCategory: "Job completion approval",
    approvalType: "job_completion_review",
    relatedObjectType: "Job",
    relatedObjectId: "job_001",
    status: "requested",
    requestedBy: "Office Admin",
    approver: "Office Admin",
    risk: "Job cannot move to billing until completion evidence is accepted.",
    targetTransition: "Job documentation_review -> approved",
    evidenceSummary: "Completion notes are present. Required install photos still need review.",
    blockingRule: "Job completion approval requires documentation review before invoice readiness.",
    decisionNotes: "Approve only after proof-of-work evidence is complete."
  },
  {
    id: "approval_005",
    approvalId: "approval_005",
    approvalCategory: "Documentation approval",
    approvalType: "documentation_review",
    relatedObjectType: "DocumentationArtifact",
    relatedObjectId: "documentation_005",
    status: "requested",
    requestedBy: "Office Admin",
    approver: "Office Admin",
    risk: "Commercial service closeout cannot move to invoice readiness until reviewed.",
    targetTransition: "Documentation submitted -> approved",
    evidenceSummary: "WilScot service notes submitted and awaiting review.",
    blockingRule: "Billing evidence must be reviewed before invoice approval.",
    decisionNotes: "Review service notes before invoice readiness."
  },
  {
    id: "approval_006",
    approvalId: "approval_006",
    approvalCategory: "Job completion approval",
    approvalType: "job_completion_review",
    relatedObjectType: "Job",
    relatedObjectId: "job_006",
    status: "held",
    requestedBy: "Dispatcher",
    approver: "Office Admin",
    risk: "VPL job cannot proceed until equipment readiness is confirmed.",
    targetTransition: "Job scheduled -> dispatch_ready",
    evidenceSummary: "Specialized install requires equipment confirmation.",
    blockingRule: "Specialized installs require prep confirmation before dispatch-ready.",
    decisionNotes: "Hold until required equipment is confirmed."
  },
  {
    id: "approval_007",
    approvalId: "approval_007",
    approvalCategory: "Documentation approval",
    approvalType: "documentation_exception",
    relatedObjectType: "DocumentationArtifact",
    relatedObjectId: "documentation_007",
    status: "held",
    requestedBy: "Office Admin",
    approver: "Office Admin",
    risk: "Missing after photos block billing readiness.",
    targetTransition: "Documentation missing -> submitted",
    evidenceSummary: "After photos are missing from the contractor closeout packet.",
    blockingRule: "Required proof-of-work must exist before invoice readiness.",
    decisionNotes: "Request missing photos from contractor."
  },
  {
    id: "approval_008",
    approvalId: "approval_008",
    approvalCategory: "Invoice approval",
    approvalType: "client_invoice_release",
    relatedObjectType: "Invoice",
    relatedObjectId: "invoice_008",
    status: "requested",
    requestedBy: "Finance",
    approver: "Michael Keegan",
    risk: "Client-facing invoice release requires final human approval.",
    targetTransition: "Invoice needs_review -> approved",
    evidenceSummary: "Completion packet approved and invoice draft ready for release review.",
    blockingRule: "Michael Keegan has MVP final authority for client-facing invoice release.",
    decisionNotes: "Approve only after reviewing packet and amount."
  }
];

export const mockContractorAssignments: ContractorAssignment[] = [
  {
    id: "assignment-1",
    jobId: "job_001",
    jobNumber: "FLR-1042",
    jobTitle: "Ramp install",
    contractorName: "Lead Installer A",
    location: "Residential site, Tampa area",
    siteContact: "M. Reynolds",
    scheduledWindow: "Today, 10:00 AM - 1:00 PM",
    status: "assigned",
    scope: "Install modular ramp and submit completion photos",
    requiredEquipment: ["Modular ramp sections", "Anchoring hardware", "Basic install tools"],
    requiredDocumentation: ["Before photos", "After photos", "Completion notes", "Safety checklist"],
    documentationStatus: "Photos pending",
    ppeRequirements: ["Gloves", "Eye protection", "Work boots"],
    safetyRequirements: ["Confirm stable surface", "Clear walking path", "Review customer access needs"],
    ppeStatus: "Compliant",
    payout: "Pending review",
    notes: "Submit proof before invoice readiness can move forward."
  },
  {
    id: "assignment-2",
    jobId: "job_002",
    jobNumber: "FLR-1048",
    jobTitle: "WilScot takedown",
    contractorName: "Senior Lead B",
    location: "Commercial site, Orlando area",
    siteContact: "Commercial coordinator",
    scheduledWindow: "This week, dispatch window pending",
    status: "accepted",
    scope: "Ramp takedown and closeout notes",
    requiredEquipment: ["Ramp removal tools", "Tie-downs", "Truck access"],
    requiredDocumentation: ["After photos", "Closeout notes", "Site condition notes"],
    documentationStatus: "Submitted",
    ppeRequirements: ["Hi-vis vest", "Gloves", "Eye protection"],
    safetyRequirements: ["Confirm commercial site access", "Check traffic exposure", "Document site condition"],
    ppeStatus: "Review needed",
    payout: "Calculated mock",
    notes: "PPE review should remain visible before final closeout."
  },
  {
    id: "assignment-4",
    jobId: "job_004",
    jobNumber: "FLR-2001",
    jobTitle: "Residential ramp install",
    contractorName: "Lead Installer A",
    location: "Residential site, Clearwater area",
    siteContact: "A. Martin",
    scheduledWindow: "Today, 1:00 PM - 4:00 PM",
    status: "assigned",
    scope: "Install residential ramp and submit before/after photos.",
    requiredEquipment: ["Ramp sections", "Anchors", "Install tools"],
    requiredDocumentation: ["Before photos", "After photos", "Completion notes"],
    documentationStatus: "Required",
    ppeRequirements: ["Gloves", "Eye protection", "Work boots"],
    safetyRequirements: ["Confirm stable landing", "Clear walkway", "Review customer mobility needs"],
    ppeStatus: "Compliant",
    payout: "Pending completion",
    notes: "Scenario 1 assignment."
  },
  {
    id: "assignment-5",
    jobId: "job_005",
    jobNumber: "FLR-2002",
    jobTitle: "WilScot service call",
    contractorName: "Senior Lead B",
    location: "Commercial site, Lakeland area",
    siteContact: "WilScot coordinator",
    scheduledWindow: "Today, commercial access window",
    status: "in_progress",
    scope: "Perform service call and document closeout conditions.",
    requiredEquipment: ["Service tools", "Replacement hardware", "Truck access"],
    requiredDocumentation: ["Service notes", "After photos", "Site condition notes"],
    documentationStatus: "Submitted",
    ppeRequirements: ["Hi-vis vest", "Gloves", "Eye protection"],
    safetyRequirements: ["Confirm site access", "Watch traffic exposure", "Document hazards"],
    ppeStatus: "Compliant",
    payout: "Pending review",
    notes: "Scenario 2 assignment."
  },
  {
    id: "assignment-6",
    jobId: "job_006",
    jobNumber: "FLR-2003",
    jobTitle: "VPL installation",
    contractorName: "Lead Installer A",
    location: "Residential site, Naples area",
    siteContact: "D. Nguyen",
    scheduledWindow: "Tomorrow, dispatch pending",
    status: "assigned",
    scope: "Prepare VPL installation and confirm required equipment.",
    requiredEquipment: ["VPL install support kit", "Lift prep tools", "Safety cones"],
    requiredDocumentation: ["Prep checklist", "Site access photos", "Equipment confirmation"],
    documentationStatus: "Required",
    ppeRequirements: ["Gloves", "Eye protection", "Work boots"],
    safetyRequirements: ["Confirm lift area clear", "Verify electrical/site readiness", "Escalate access issues"],
    ppeStatus: "Compliant",
    payout: "Not calculated",
    notes: "Scenario 3 assignment."
  },
  {
    id: "assignment-7",
    jobId: "job_007",
    jobNumber: "FLR-2004",
    jobTitle: "Ramp takedown",
    contractorName: "Helper C",
    location: "Residential site, Fort Myers area",
    siteContact: "C. Brooks",
    scheduledWindow: "Yesterday",
    status: "transfer_requested",
    scope: "Complete takedown and upload after photos.",
    remainingScope: "Return to verify site condition, capture after photos, and close out the documentation blocker.",
    transferReason: "Helper C submitted partial work but cannot complete required after-photo verification.",
    transferTarget: "Lead Installer A or Senior Lead B",
    transferPacketSummary:
      "Transfer packet holds payout and invoice readiness until the replacement contractor submits final evidence.",
    requiredEquipment: ["Removal tools", "Truck access"],
    requiredDocumentation: ["After photos", "Completion notes"],
    documentationStatus: "Missing after photos",
    ppeRequirements: ["Gloves", "Eye protection"],
    safetyRequirements: ["Document site condition", "Confirm no remaining trip hazard"],
    ppeStatus: "Compliant",
    payout: "Held",
    notes: "Scenario 4 assignment moved into transfer review because the job is partial and documentation is missing."
  },
  {
    id: "assignment-8",
    jobId: "job_008",
    jobNumber: "FLR-2005",
    jobTitle: "Commercial ramp install",
    contractorName: "Senior Lead B",
    location: "Commercial site, Jacksonville area",
    siteContact: "Facilities manager",
    scheduledWindow: "Completed this week",
    status: "submitted",
    scope: "Install commercial ramp and submit complete closeout packet.",
    requiredEquipment: ["Commercial ramp kit", "Install tools", "Truck access"],
    requiredDocumentation: ["Completion packet", "After photos", "Customer signoff"],
    documentationStatus: "Approved",
    ppeRequirements: ["Hi-vis vest", "Gloves", "Eye protection", "Work boots"],
    safetyRequirements: ["Verify ADA path", "Document final condition", "Confirm site contact signoff"],
    ppeStatus: "Compliant",
    payout: "Pending invoice approval",
    notes: "Scenario 5 assignment ready for invoice approval."
  }
];

export const coreRecordLookups = {
  leads: (id: string) => mockLeads.find((record) => record.id === id),
  customers: (id: string) => mockCustomers.find((record) => record.id === id),
  jobs: (id: string) => mockJobs.find((record) => record.id === id),
  contractors: (id: string) => mockContractors.find((record) => record.id === id),
  communications: (id: string) => mockCommunications.find((record) => record.id === id),
  documentation: (id: string) => mockDocumentation.find((record) => record.id === id),
  invoices: (id: string) => mockInvoices.find((record) => record.id === id),
  alerts: (id: string) => mockAlerts.find((record) => record.id === id),
  approvals: (id: string) => mockApprovals.find((record) => record.id === id)
};

export const demoScenarios: DemoScenario[] = [
  {
    id: "scenario_001",
    title: "Residential Ramp Install",
    summary: "Assigned residential ramp job moving from dispatch into contractor acceptance and documentation.",
    stage: "Assignment",
    leadId: "lead_004",
    customerId: "customer_004",
    jobId: "job_004",
    contractorId: "contractor_001",
    communicationId: "communication_004",
    documentationId: "documentation_004",
    invoiceId: "invoice_004",
    alertId: "alert_004",
    approvalId: "approval_004",
    assignmentId: "assignment-4",
    validation: {
      lead: "Manual customer intake confirmed",
      job: "Job assigned",
      assignment: "Contractor acceptance pending",
      documentation: "Required before completion",
      approval: "Job completion approval pending later",
      invoiceReadiness: "Not ready"
    }
  },
  {
    id: "scenario_002",
    title: "WilScot Service Call",
    summary: "Commercial service call with submitted documentation and follow-up review.",
    stage: "Documentation Review",
    leadId: "lead_005",
    customerId: "customer_005",
    jobId: "job_005",
    contractorId: "contractor_002",
    communicationId: "communication_005",
    documentationId: "documentation_005",
    invoiceId: "invoice_005",
    alertId: "alert_005",
    approvalId: "approval_005",
    assignmentId: "assignment-5",
    validation: {
      lead: "Commercial account request received",
      job: "Job in progress",
      assignment: "Contractor working service call",
      documentation: "Service notes submitted",
      approval: "Documentation approval requested",
      invoiceReadiness: "Waiting on review"
    }
  },
  {
    id: "scenario_003",
    title: "VPL Installation",
    summary: "Specialized VPL installation scheduled with equipment confirmation required before dispatch-ready.",
    stage: "Scheduled",
    leadId: "lead_006",
    customerId: "customer_006",
    jobId: "job_006",
    contractorId: "contractor_001",
    communicationId: "communication_006",
    documentationId: "documentation_006",
    invoiceId: "invoice_006",
    alertId: "alert_006",
    approvalId: "approval_006",
    assignmentId: "assignment-6",
    validation: {
      lead: "VPL request captured",
      job: "Job scheduled",
      assignment: "Contractor assigned",
      documentation: "Prep checklist required",
      approval: "Dispatch readiness held",
      invoiceReadiness: "Not ready"
    }
  },
  {
    id: "scenario_004",
    title: "Contractor Documentation Missing",
    summary: "Completed field work blocked because required after photos are missing.",
    stage: "Blocked",
    leadId: "lead_007",
    customerId: "customer_007",
    jobId: "job_007",
    contractorId: "contractor_003",
    communicationId: "communication_007",
    documentationId: "documentation_007",
    invoiceId: "invoice_007",
    alertId: "alert_007",
    approvalId: "approval_007",
    assignmentId: "assignment-7",
    validation: {
      lead: "Customer work completed",
      job: "Job in transfer review",
      assignment: "Transfer requested",
      documentation: "After photos missing",
      approval: "Documentation exception held",
      invoiceReadiness: "Blocked"
    }
  },
  {
    id: "scenario_005",
    title: "Invoice Ready For Approval",
    summary: "Commercial install has approved documentation and is waiting for Michael invoice release approval.",
    stage: "Invoice Review",
    leadId: "lead_008",
    customerId: "customer_008",
    jobId: "job_008",
    contractorId: "contractor_002",
    communicationId: "communication_008",
    documentationId: "documentation_008",
    invoiceId: "invoice_008",
    alertId: "alert_008",
    approvalId: "approval_008",
    assignmentId: "assignment-8",
    validation: {
      lead: "Commercial request completed",
      job: "Job in invoice review",
      assignment: "Completion packet submitted",
      documentation: "Approved",
      approval: "Michael invoice approval requested",
      invoiceReadiness: "Ready"
    }
  }
];
